version: '3'
services:
  odoo-stack:
    container_name: odoo-stack
    build:
      context: ./Dockerfiles
      dockerfile: odoo.Dockerfile
    volumes:
      - ./addons-extra:/mnt/extra-addons
      - ./odoo-config:/etc/odoo
      - odoo-web-data:/var/lib/odoo
    ports:
      - 8069:8069
    depends_on:
      - database-stack
    restart: always
  pgadmin-stack:
    container_name: pgadmin-stack
    image: dpage/pgadmin4:5.4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 8080:80
    links:
      - "database-stack:pgsql-server"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@united360.in
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PGADMIN_LISTEN_PORT=80
    depends_on:
      - database-stack
    restart: always
  database-stack:
    container_name: database-stack
    image: postgres:latest
    volumes:
      - database-stack-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
  nginx-stack:
    container_name: nginx-stack
    depends_on:
      - odoo-stack
      - database-stack
    restart: always
    build:
      dockerfile: nginx.Dockerfile
      context: ./Dockerfiles
    ports:
      - '80:80'
volumes:
  database-stack-data:
  pgadmin-data:
  odoo-web-data:
